# Gunakan Node.js image resmi
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files dan install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

COPY prisma ./prisma

# Build TypeScript
RUN npm run build

# Jalankan aplikasi
CMD ["node", "dist/app.js"]
